esphome:
  name: belliot
  platform: ESP8266
  board: d1_mini

switch:
  # control relay for opener
  - platform: gpio
    name: "Door Opener"
    pin: D1
    id: door_opener
    icon: "mdi:door-open"
    on_turn_on:
      - delay: 3000ms
      - switch.turn_off: door_opener

  # control relay for bell signal
  - platform: gpio
    name: "Bell Signal"
    pin: D2
    inverted: true
    id: bell
    icon: "mdi:bell-ring"
    restore_mode: RESTORE_DEFAULT_ON

  # template switch to control auto door open on ring
  - platform: template
    name: "Auto Door Open"
    id: auto_door_open
    turn_on_action:
      - switch.template.publish:
          id: auto_door_open
          state: !lambda 'return true;'
    turn_off_action:
      - switch.template.publish:
          id: auto_door_open
          state: !lambda 'return false;'

binary_sensor:
  # gpio in for actual door bell button
  - platform: gpio
    name: "Door Bell Button"
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_off: 500ms
    on_press:
      then:
      - delay: 1s
      - if:
          condition:
            - switch.is_on: auto_door_open
          then:
            - switch.toggle: door_opener

  # button to silent the door bell (located on belliot)
  - platform: gpio
    name: "Bell Silent Button"
    pin:
      number: D6
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 40ms
    on_press:
      then:
        - switch.toggle: bell

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ap_ssid
    password: !secret wifi_ap_password

captive_portal:
